site_name: AI-Racer
site_url: https://marcussyl.github.io/deepracer/
nav:
  - Home: index.md
  - Events: events.md
  - Reinforcement Learning: reinforcement_learning_intro.md
  - Tutorials: tutorial.md
  - Gallery: gallery.md
  # - Rules and Guidelines: rules_and_guidelines.md
theme:
  favicon: img/favicon.png
  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: navy
      accent: navy
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: navy
      accent: navy

plugins:
  # - social
  # - table-reader
  # - glightbox
  # - gallery:
  #     examples_dirs: docs/examples          # path to your example scripts
  #     gallery_dirs: docs/generated/gallery  # where to save generated gallery

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/
#     - icon: fontawesome/brands/twitter
#       link: https://github.com/
#     - icon: fontawesome/brands/linkedin
#       link: https://github.com/

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/Marcussyl"  target="_blank" rel="noopener">HKU</a>
